// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/openshift/custom-resource-status/conditions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPathProvisioner) DeepCopyInto(out *HostPathProvisioner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPathProvisioner.
func (in *HostPathProvisioner) DeepCopy() *HostPathProvisioner {
	if in == nil {
		return nil
	}
	out := new(HostPathProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostPathProvisioner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPathProvisionerList) DeepCopyInto(out *HostPathProvisionerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostPathProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPathProvisionerList.
func (in *HostPathProvisionerList) DeepCopy() *HostPathProvisionerList {
	if in == nil {
		return nil
	}
	out := new(HostPathProvisionerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostPathProvisionerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPathProvisionerSpec) DeepCopyInto(out *HostPathProvisionerSpec) {
	*out = *in
	out.PathConfig = in.PathConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPathProvisionerSpec.
func (in *HostPathProvisionerSpec) DeepCopy() *HostPathProvisionerSpec {
	if in == nil {
		return nil
	}
	out := new(HostPathProvisionerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPathProvisionerStatus) DeepCopyInto(out *HostPathProvisionerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPathProvisionerStatus.
func (in *HostPathProvisionerStatus) DeepCopy() *HostPathProvisionerStatus {
	if in == nil {
		return nil
	}
	out := new(HostPathProvisionerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathConfig) DeepCopyInto(out *PathConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathConfig.
func (in *PathConfig) DeepCopy() *PathConfig {
	if in == nil {
		return nil
	}
	out := new(PathConfig)
	in.DeepCopyInto(out)
	return out
}
